apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sut-java-8
  namespace: perf-test
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-workflow
  entrypoint: sut
  templates:
  - name: sut
    steps:
    - - name: sut-server
        template: run-java
        arguments:
          parameters:
          - name: image
            valueFrom:
              configMapKeyRef:
                name: sut-repo
                key: ecr-url
          - name: tag
            value: '4.1.2-corretto-8'

    - - name: wrk
        template: run-wrk
        arguments:
          parameters:
          - name: c
            value: '100'
          - name: server-ip
            value: "{{steps.sut-server.ip}}"

  - name: run-java
    daemon: true
    inputs:
      parameters:
      - name: image
      - name: tag
    nodeSelector:
      node.kubernetes.io/instance-type: m7g.xlarge
    container:
      image: "{{inputs.parameters.image}}:{{inputs.parameters.tag}}"
      command: ["java"]
      args:
      - -XX:+PerfDisableSharedMem
      - -XX:+UseG1GC
      - -jar
      - target/web-bookshop-4.1.2-fat.jar
      resources:
        requests:
          cpu: 1

  - name: run-wrk
    inputs:
      parameters:
      - name: c
      - name: server-ip
    nodeSelector:
      node.kubernetes.io/instance-type: m5.xlarge
    container:
      image: bootjp/wrk2:latest
      command: ["wrk"]
      args:
      - -t2
      - -c{{inputs.parameters.c}}
      - -d30s
      - -R2000
      - --latency
      - http://{{inputs.parameters.server-ip}}:8080/books
      resources:
        requests:
          memory: 256Mi
          cpu: 1
