apiVersion: v1
kind: Secret
metadata:
  name: argo-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: argo-workflows-server
type: kubernetes.io/service-account-token
